name: CI

on:
  push:
    tags:
      - "v*"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.87.0
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
  publish:
    name: Publish
    if: startsWith( github.ref, 'refs/tags/v' )
    uses: ./.github/workflows/release.yml
    needs: build
    secrets: inherit